plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'org.springframework.boot'
}

dependencies {
    api 'com.fasterxml.jackson.core:jackson-annotations'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind'
    testImplementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    testImplementation 'com.fasterxml.jackson.module:jackson-module-kotlin'
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

kotlin {
    compilerOptions {
        freeCompilerArgs.addAll '-Xjsr305=strict', '-Xannotation-default-target=param-property'
    }
}
